import type { NextPage } from 'next';
import Head from 'next/head';
import axios from "axios";
import { GetServerSideProps } from "next";
//コンポーネント


// export const getServerSideProps: GetServerSideProps<SSRProps> = async (context) => {
//   const allPostsData = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/post/${process.env.USER_ID}`);
//   //最新の記事6件表示　API側で書き換えること
//   const recentPostData = allPostsData.data.slice(0, 6)
//   return {
//     props: {
//       recentPostData
//     },
//   };
// };
//
// type SSRProps = {
//   recentPostData: any
// }

const Home: NextPage = (props) => {
  return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/frontend/public/favicon.ico" />
        </Head>

      </div>
  );
};

export default Home;