import type { NextPage } from 'next';
import Head from 'next/head';
import axios from "axios";
import { GetServerSideProps } from "next";
import ArticleHeadingListLayout from "../src/components/ArticleHeadingListLayout";
//コンポーネント


export const getServerSideProps: GetServerSideProps<SSRProps> = async (context) => {
    //最新の記事を6件取得
    const data = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/post/${process.env.USER_ID}/category/2222`,{
        data: {
            skip: 0,
            take: 6,
        }
    });
    console.log(data);
    const recentPostData = data.data
    return {
        props: {
            recentPostData
        },
    };
};

type SSRProps = {
    recentPostData: any
}

const TestCom: NextPage<SSRProps> = ({recentPostData}) => {
    console.log(recentPostData)
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/frontend/public/favicon.ico" />
            </Head>
            api test
        </>
    );
};

export default TestCom;